# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 642)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(46, 52, 54)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioEnglish = QtWidgets.QRadioButton(self.centralwidget)
        self.radioEnglish.setGeometry(QtCore.QRect(680, 20, 112, 23))
        self.radioEnglish.setStyleSheet("color: rgb(52, 101, 164);\n"
"alternate-background-color: rgb(136, 138, 133);\n"
"font-weight: bold;")
        self.radioEnglish.setObjectName("radioEnglish")
        self.buttonGroup_Languages = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_Languages.setObjectName("buttonGroup_Languages")
        self.buttonGroup_Languages.addButton(self.radioEnglish)
        self.radioMagyar = QtWidgets.QRadioButton(self.centralwidget)
        self.radioMagyar.setGeometry(QtCore.QRect(680, 50, 112, 23))
        self.radioMagyar.setStyleSheet("color: rgb(204, 0, 0);")
        self.radioMagyar.setObjectName("radioMagyar")
        self.buttonGroup_Languages.addButton(self.radioMagyar)
        self.checkBox_Translation = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Translation.setGeometry(QtCore.QRect(20, 10, 111, 23))
        self.checkBox_Translation.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(211, 215, 207);")
        self.checkBox_Translation.setCheckable(True)
        self.checkBox_Translation.setChecked(True)
        self.checkBox_Translation.setObjectName("checkBox_Translation")
        self.checkBox_Word = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Word.setGeometry(QtCore.QRect(20, 40, 111, 23))
        self.checkBox_Word.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(211, 215, 207);\n"
"text-align: center;")
        self.checkBox_Word.setObjectName("checkBox_Word")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 100, 681, 401))
        self.tabWidget.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.lineEdit_translation = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_translation.setGeometry(QtCore.QRect(440, 100, 171, 31))
        self.lineEdit_translation.setStyleSheet("background-color: rgb(233, 185, 110);\n"
"color: rgb(85, 87, 83);\n"
"\n"
"font: 57 11pt \"Ubuntu\";\n"
"font-weight: bold;")
        self.lineEdit_translation.setText("")
        self.lineEdit_translation.setObjectName("lineEdit_translation")
        self.pushButton_get_new_word = QtWidgets.QPushButton(self.tab)
        self.pushButton_get_new_word.setGeometry(QtCore.QRect(240, 30, 181, 41))
        self.pushButton_get_new_word.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_get_new_word.setAccessibleDescription("")
        self.pushButton_get_new_word.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"font: 57 14pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"color: rgb(136, 138, 133);\n"
"\n"
"QPushButton::hover {\n"
"    color: rgb(254, 0, 0);\n"
"}")
        self.pushButton_get_new_word.setObjectName("pushButton_get_new_word")
        self.lineEdit_word = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_word.setGeometry(QtCore.QRect(30, 100, 181, 31))
        self.lineEdit_word.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(233, 185, 110);\n"
"\n"
"font: 57 11pt \"Ubuntu\";\n"
"font-weight: bold;")
        self.lineEdit_word.setText("")
        self.lineEdit_word.setObjectName("lineEdit_word")
        self.pushButton_get_translation = QtWidgets.QPushButton(self.tab)
        self.pushButton_get_translation.setGeometry(QtCore.QRect(400, 260, 181, 41))
        self.pushButton_get_translation.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_get_translation.setAccessibleDescription("")
        self.pushButton_get_translation.setStyleSheet("background-color: rgb(252, 175, 62);\n"
"font: 50 13pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"color: ;\n"
"color: rgb(85, 87, 83);\n"
"\n"
"QPushButton::hover {\n"
"    color: rgb(254, 0, 0);\n"
"}")
        self.pushButton_get_translation.setObjectName("pushButton_get_translation")
        self.pushButton_get_word = QtWidgets.QPushButton(self.tab)
        self.pushButton_get_word.setGeometry(QtCore.QRect(50, 260, 181, 41))
        self.pushButton_get_word.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_get_word.setAccessibleDescription("")
        self.pushButton_get_word.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(233, 185, 110);\n"
"font: 57 15pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"\n"
"pushButton_get_word::hover {\n"
"    color: rgb(254, 0, 0);\n"
"}")
        self.pushButton_get_word.setObjectName("pushButton_get_word")
        self.label_words_number = QtWidgets.QLabel(self.tab)
        self.label_words_number.setGeometry(QtCore.QRect(286, 100, 61, 21))
        self.label_words_number.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(186, 189, 182);")
        self.label_words_number.setObjectName("label_words_number")
        self.pushButton_prev_word = QtWidgets.QPushButton(self.tab)
        self.pushButton_prev_word.setGeometry(QtCore.QRect(230, 180, 181, 41))
        self.pushButton_prev_word.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_prev_word.setAccessibleDescription("")
        self.pushButton_prev_word.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"font: 57 14pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"color: rgb(136, 138, 133);\n"
"\n"
"QPushButton::hover {\n"
"    color: rgb(254, 0, 0);\n"
"}")
        self.pushButton_prev_word.setObjectName("pushButton_prev_word")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(260, 130, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.checkBox_to_top = QtWidgets.QCheckBox(self.tab)
        self.checkBox_to_top.setGeometry(QtCore.QRect(30, 140, 92, 23))
        self.checkBox_to_top.setObjectName("checkBox_to_top")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_meaning = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_meaning.setGeometry(QtCore.QRect(470, 110, 171, 31))
        self.lineEdit_meaning.setStyleSheet("background-color: rgb(233, 185, 110);\n"
"color: rgb(85, 87, 83);\n"
"\n"
"font: 57 11pt \"Ubuntu\";\n"
"font-weight: bold;")
        self.lineEdit_meaning.setText("")
        self.lineEdit_meaning.setObjectName("lineEdit_meaning")
        self.pushButton_get_meaning = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_get_meaning.setGeometry(QtCore.QRect(430, 270, 181, 41))
        self.pushButton_get_meaning.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_get_meaning.setAccessibleDescription("")
        self.pushButton_get_meaning.setStyleSheet("background-color: rgb(252, 175, 62);\n"
"font: 50 13pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"color: ;\n"
"color: rgb(85, 87, 83);\n"
"\n"
"QPushButton::hover {\n"
"    color: rgb(254, 0, 0);\n"
"}")
        self.pushButton_get_meaning.setObjectName("pushButton_get_meaning")
        self.pushButton_get_term = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_get_term.setGeometry(QtCore.QRect(80, 270, 181, 41))
        self.pushButton_get_term.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_get_term.setAccessibleDescription("")
        self.pushButton_get_term.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(233, 185, 110);\n"
"font: 57 15pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"\n"
"pushButton_get_word::hover {\n"
"    color: rgb(254, 0, 0);\n"
"}")
        self.pushButton_get_term.setObjectName("pushButton_get_term")
        self.pushButton_get_new_term = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_get_new_term.setGeometry(QtCore.QRect(270, 40, 181, 41))
        self.pushButton_get_new_term.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_get_new_term.setAccessibleDescription("")
        self.pushButton_get_new_term.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"font: 57 14pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"color: rgb(136, 138, 133);\n"
"\n"
"QPushButton::hover {\n"
"    color: rgb(254, 0, 0);\n"
"}")
        self.pushButton_get_new_term.setObjectName("pushButton_get_new_term")
        self.lineEdit_term = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_term.setGeometry(QtCore.QRect(60, 110, 181, 31))
        self.lineEdit_term.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(233, 185, 110);\n"
"\n"
"font: 57 11pt \"Ubuntu\";\n"
"font-weight: bold;")
        self.lineEdit_term.setText("")
        self.lineEdit_term.setObjectName("lineEdit_term")
        self.radioTerms = QtWidgets.QRadioButton(self.tab_3)
        self.radioTerms.setGeometry(QtCore.QRect(530, 10, 112, 23))
        self.radioTerms.setStyleSheet("color: rgb(204, 200, 0);\n"
"background-color: rgb(46, 52, 54);")
        self.radioTerms.setObjectName("radioTerms")
        self.buttonGroup_TermsDates = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_TermsDates.setObjectName("buttonGroup_TermsDates")
        self.buttonGroup_TermsDates.addButton(self.radioTerms)
        self.radioDates = QtWidgets.QRadioButton(self.tab_3)
        self.radioDates.setGeometry(QtCore.QRect(530, 40, 112, 23))
        self.radioDates.setStyleSheet("color: rgb(204, 200, 0);\n"
"background-color: rgb(46, 52, 54);")
        self.radioDates.setObjectName("radioDates")
        self.buttonGroup_TermsDates.addButton(self.radioDates)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_word_towrite = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_word_towrite.setEnabled(True)
        self.lineEdit_word_towrite.setGeometry(QtCore.QRect(90, 190, 121, 25))
        self.lineEdit_word_towrite.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(238, 238, 236);")
        self.lineEdit_word_towrite.setText("")
        self.lineEdit_word_towrite.setFrame(True)
        self.lineEdit_word_towrite.setObjectName("lineEdit_word_towrite")
        self.lineEdit_translation_towrite = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_translation_towrite.setGeometry(QtCore.QRect(270, 190, 113, 25))
        self.lineEdit_translation_towrite.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(238, 238, 236);")
        self.lineEdit_translation_towrite.setText("")
        self.lineEdit_translation_towrite.setObjectName("lineEdit_translation_towrite")
        self.pushButton_write = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_write.setGeometry(QtCore.QRect(100, 240, 171, 25))
        self.pushButton_write.setObjectName("pushButton_write")
        self.radioOneWord_towrite = QtWidgets.QRadioButton(self.tab_2)
        self.radioOneWord_towrite.setGeometry(QtCore.QRect(390, 20, 112, 23))
        self.radioOneWord_towrite.setChecked(True)
        self.radioOneWord_towrite.setObjectName("radioOneWord_towrite")
        self.buttonGroup_writeMode = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_writeMode.setObjectName("buttonGroup_writeMode")
        self.buttonGroup_writeMode.addButton(self.radioOneWord_towrite)
        self.radioText_towrite = QtWidgets.QRadioButton(self.tab_2)
        self.radioText_towrite.setGeometry(QtCore.QRect(390, 50, 112, 23))
        self.radioText_towrite.setObjectName("radioText_towrite")
        self.buttonGroup_writeMode.addButton(self.radioText_towrite)
        self.Text_towrite = QtWidgets.QPlainTextEdit(self.tab_2)
        self.Text_towrite.setGeometry(QtCore.QRect(90, 20, 291, 201))
        self.Text_towrite.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(238, 238, 236);")
        self.Text_towrite.setCenterOnScroll(True)
        self.Text_towrite.setPlaceholderText("")
        self.Text_towrite.setObjectName("Text_towrite")
        self.label_writeTip = QtWidgets.QLabel(self.tab_2)
        self.label_writeTip.setGeometry(QtCore.QRect(100, 280, 321, 21))
        self.label_writeTip.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(233, 185, 110);")
        self.label_writeTip.setObjectName("label_writeTip")
        self.label_wordTip = QtWidgets.QLabel(self.tab_2)
        self.label_wordTip.setGeometry(QtCore.QRect(90, 150, 121, 21))
        self.label_wordTip.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(233, 185, 110);")
        self.label_wordTip.setObjectName("label_wordTip")
        self.label_translationTip = QtWidgets.QLabel(self.tab_2)
        self.label_translationTip.setGeometry(QtCore.QRect(270, 150, 121, 21))
        self.label_translationTip.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(233, 185, 110);")
        self.label_translationTip.setObjectName("label_translationTip")
        self.lineEdit_translation_towrite.raise_()
        self.pushButton_write.raise_()
        self.radioOneWord_towrite.raise_()
        self.radioText_towrite.raise_()
        self.lineEdit_word_towrite.raise_()
        self.Text_towrite.raise_()
        self.label_writeTip.raise_()
        self.label_wordTip.raise_()
        self.label_translationTip.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(450, 550, 131, 41))
        self.pushButton_exit.setStyleSheet("color: rgb(186, 189, 182);\n"
"font-size: 20px;")
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.radioOneWord_towrite.clicked.connect(self.Text_towrite.hide)
        self.radioText_towrite.clicked.connect(self.Text_towrite.show)
        self.radioText_towrite.clicked.connect(self.lineEdit_word_towrite.hide)
        self.radioText_towrite.clicked.connect(self.lineEdit_translation_towrite.hide)
        self.radioOneWord_towrite.clicked.connect(self.lineEdit_word_towrite.show)
        self.radioOneWord_towrite.clicked.connect(self.lineEdit_translation_towrite.show)
        self.radioText_towrite.clicked.connect(self.label_writeTip.show)
        self.radioOneWord_towrite.clicked.connect(self.label_writeTip.hide)
        self.radioOneWord_towrite.clicked.connect(self.label_wordTip.show)
        self.radioOneWord_towrite.clicked.connect(self.label_translationTip.show)
        self.radioText_towrite.clicked.connect(self.label_wordTip.hide)
        self.radioText_towrite.clicked.connect(self.label_translationTip.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioEnglish.setText(_translate("MainWindow", "English"))
        self.radioMagyar.setText(_translate("MainWindow", "Magyar"))
        self.checkBox_Translation.setText(_translate("MainWindow", "Translation"))
        self.checkBox_Word.setText(_translate("MainWindow", "Word"))
        self.pushButton_get_new_word.setText(_translate("MainWindow", "Get a new word"))
        self.pushButton_get_translation.setText(_translate("MainWindow", "Get the translation"))
        self.pushButton_get_word.setText(_translate("MainWindow", "Get a word"))
        self.label_words_number.setText(_translate("MainWindow", "0"))
        self.pushButton_prev_word.setText(_translate("MainWindow", "Previous word"))
        self.checkBox_to_top.setText(_translate("MainWindow", "В начало"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.pushButton_get_meaning.setText(_translate("MainWindow", "Get the meaning"))
        self.pushButton_get_term.setText(_translate("MainWindow", "Get a term"))
        self.pushButton_get_new_term.setText(_translate("MainWindow", "Get a new term"))
        self.radioTerms.setText(_translate("MainWindow", "Terms"))
        self.radioDates.setText(_translate("MainWindow", "Dates"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Страница"))
        self.pushButton_write.setText(_translate("MainWindow", "Записать слово"))
        self.radioOneWord_towrite.setText(_translate("MainWindow", "Одно слово"))
        self.radioText_towrite.setText(_translate("MainWindow", "Текст"))
        self.label_writeTip.setText(_translate("MainWindow", "Words are supposed to be : word-translation"))
        self.label_wordTip.setText(_translate("MainWindow", "Word"))
        self.label_translationTip.setText(_translate("MainWindow", "Translation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
